name: soul_connect
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  get: ^4.6.6
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.13.1
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.3.3
  cached_network_image: ^3.3.0
  animations: ^2.0.8
  logger: ^2.0.2+1
  pretty_dio_logger: ^1.3.1
  flutter_keyboard_visibility: ^5.4.1
  smooth_page_indicator: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  otp_text_field: ^1.1.3
  photo_manager: ^2.7.2
  wechat_assets_picker: ^8.7.1
  path_provider: ^2.1.1
  visibility_detector: ^0.4.0+2
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  device_info_plus: 9.0.3
  permission_handler: ^11.0.1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  google_sign_in: ^6.1.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  the_apple_sign_in: ^1.1.1
  reorderables: ^0.6.0
  url_launcher: ^6.1.14
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.2.2
  avatar_glow: ^2.0.2
  country_code_picker: ^3.0.0
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  flutter_card_swiper: ^6.0.0
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.3

flutter:
  
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins-M
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-B
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-SB
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-R
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-M-I
      fonts:
        - asset: assets/fonts/Poppins-MediumItalic.ttf